import HadoukenWrapper from "@/components/hadouken";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" className="h-full">
      <body className="relative bg-slate-200 h-full">
        <HadoukenWrapper>
          <div className="flex h-full flex-col">
            <div className="h-full">{children}</div>
          </div>
        </HadoukenWrapper>
      </body>
    </html>
  );
}
