import HadoukenWrapper from "@/components/hadouken";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" className="h-full">
      <body className="relative h-full overflow-hidden" style={{
        perspective: "1000px",
        perspectiveOrigin: "50% 50%",
      }}>
        <HadoukenWrapper className="h-full overflow-y-auto overflow-x-hidden bg-slate-200 ">
          {children}
        </HadoukenWrapper>
      </body>
    </html>
  );
}
